#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t eatery --no-cache .
docker tag $(docker images -q eatery) cornellappdev/eatery:"$TRAVIS_COMMIT"
docker push cornellappdev/eatery:"$TRAVIS_COMMIT"
